[package]
name = "hash-rs"
version = "0.1.0"
authors = ["Alexis Beingessner <a.beingessner@gmail.com>"]

[dependencies]
twox-hash = "*"
# murmurhash64 = "*"
murmurhash3 = "*"
fnv = "*"
blake2-rfc = "*"
regex = "1.1.2"
rand = "0.6.5"
ahash = "*"
