[package]
name = "hash-rs"
version = "0.1.0"
authors = ["Alexis Beingessner <a.beingessner@gmail.com>"]

[dependencies]
twox-hash = "*"
# murmurhash64 = "*"
murmurhash3 = "*"
farmhash = "*"
fnv = "*"
blake2-rfc = "*"
regex = "*"
